import type { Schedule } from './schedule';
import { timeToMin } from './schedule';

export type NotifyPoint = {
  time: string; // "HH:MM"
  message: string;
};

/** Schedule から通知ポイントを算出（各タスク終了5分前、過去はスキップ） */
export function calcNotifyPoints(
  schedule: Schedule,
  now: string,
): NotifyPoint[] {
  const nowMin = timeToMin(now);
  const points: NotifyPoint[] = [];

  for (let i = 0; i < schedule.blocks.length; i++) {
    const block = schedule.blocks[i]!;
    const endMin = timeToMin(block.end);
    const notifyMin = endMin - 5;

    if (notifyMin <= nowMin) continue;
    if (block.kind === 'other') continue;

    const next = schedule.blocks[i + 1];
    const message = next
      ? `「${block.task}」終了5分前 → 次: ${next.task}`
      : `「${block.task}」終了5分前`;

    points.push({
      time: minToTime(notifyMin),
      message,
    });
  }

  return points;
}

/** 通知シェルスクリプトを生成 */
export function generateNotifyScript(points: NotifyPoint[]): string {
  const lines: string[] = [
    '#!/bin/bash',
    '# Generated by dayplan. Do not edit.',
    '',
  ];

  for (const p of points) {
    const escapedMsg = p.message.replace(/"/g, '\\"');
    lines.push(
      `( sleep $(( $(date -j -f "%H:%M" "${p.time}" "+%s") - $(date "+%s") )) 2>/dev/null && osascript -e 'display notification "${escapedMsg}" with title "dayplan"' ) &`,
    );
  }

  lines.push('');
  lines.push('wait');
  lines.push('');

  return lines.join('\n');
}

/** launchd plist を生成 */
export function generatePlist(scriptPath: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.dayplan.notify</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/bash</string>
		<string>${scriptPath}</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
`;
}

function minToTime(min: number): string {
  const h = Math.floor(min / 60);
  const m = min % 60;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
}
